server:
  port: 80

spring:
#  application:
#    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 可以从nacos 中发现微服务z
      routes:
        #访问http://localhost:80/test/news 就可以转发到http://news.baidu.com/guonei
        - id: payment_routes2
          uri: http://news.baidu.com/
          predicates:
            - Path=/api/test/**

        - id: auth
#          uri: http://localhost:8100
          uri: lb://auth-service # lb 表示 从nacos 中按照名称获取微服务，并遵循负载均衡策略, auth-service 即微服务注册名
          predicates:
            - Path=/api/auth/**

        - id: user
          #          uri: http://localhost:8100
          uri: lb://user-service # lb 表示 从nacos 中按照名称获取微服务，并遵循负载均衡策略, auth-service 即微服务注册名
          predicates:
            - Path=/api/user/**

        - id: system
          #          uri: http://localhost:8100
          uri: lb://system-service # lb 表示 从nacos 中按照名称获取微服务，并遵循负载均衡策略, auth-service 即微服务注册名
          predicates:
            - Path=/api/system/**

        - id: demo
          uri: lb://demo-service
          predicates:
            - Path=/api/demo/**
    loadbalancer:
      nacos:
        enabled: true